options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1: Git Prep (Explicitly rooted in /workspace)
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  dir: '/workspace'  # <--- EXPLICITLY DEFINED WORK DIRECTORY
  script: |
    #!/usr/bin/env bash
    git config --global user.email "ralph-agent@bilkobibitkov.com"
    git config --global user.name "Ralph Agent"
    git remote set-url origin https://$$GH_TOKEN@github.com/BilkoBibitkov/bilko-bridge.git
    git checkout -B main
    if [ -f "PRD.json" ]; then cp PRD.json prd.json; fi

# Step 2: Probe & Evolution (Ralph Brain)
- name: 'gcr.io/bilkobibitkov/ralph-brain:latest'
  secretEnv: ['GOOGLE_API_KEY']
  dir: '/workspace' # Ensure Ralph also starts in the root
  script: |
    #!/usr/bin/env bash
    # 1. Run the Probe (curl is pre-installed in ralph-brain)
    chmod +x probe.sh
    ./probe.sh
    
    # 2. Run Ralph (python & google-genai are pre-installed in ralph-brain)
    chmod +x ralph.sh
    ./ralph.sh 5

# Step 3: Next.js Build
- name: 'node:20'
  dir: '/workspace'
  script: |
    #!/usr/bin/env bash
    npm install
    npm run build

# Step 4: Firebase Deploy
- name: 'gcr.io/bilkobibitkov/firebase'
  dir: '/workspace'
  args: ['deploy', '--only', 'hosting', '--project', 'bilkobibitkov']

# Step 5: Sync
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  dir: '/workspace'
  script: |
    #!/usr/bin/env bash
    git add .
    git commit -m "chore: Ralph evolution update [skip ci]" || echo "No changes"
    git push origin main

availableSecrets:
  secretManager:
  - versionName: projects/bilkobibitkov/secrets/GITHUB_PAT/versions/latest
    env: 'GH_TOKEN'
  - versionName: projects/bilkobibitkov/secrets/GEMINI_API_KEY/versions/latest
    env: 'GOOGLE_API_KEY'