steps:
# Step 1: Git & Branch Prep
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  script: |
    #!/usr/bin/env bash
    git config --global user.email "ralph-agent@bilkobibitkov.com"
    git config --global user.name "Ralph Agent"
    git remote set-url origin https://\${GH_TOKEN}@github.com/BilkoBibitkov/bilko-bridge.git
    git checkout -B main
    if [ -f "PRD.json" ]; then cp PRD.json prd.json; fi

# Step 2: Evolution (Ralph)
- name: 'python:3.11'
  secretEnv: ['GEMINI_API_KEY']
  # This 'env' block is the key to fixing the Python visibility issue
  env:
    - 'GEMINI_API_KEY=\${GEMINI_API_KEY}'
  script: |
    #!/usr/bin/env bash
    pip install google-genai
    chmod +x ralph.sh
    ./ralph.sh 5

# Step 3: Next.js Build
- name: 'node:20'
  script: |
    #!/usr/bin/env bash
    npm install
    npm run build

# Step 4: Firebase Deploy
- name: 'gcr.io/cloud-builders/firebase'
  args: ['deploy', '--only', 'hosting', '--project', 'bilkobibitkov']

# Step 5: Sync Evolution back to GitHub
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  script: |
    #!/usr/bin/env bash
    git add .
    git commit -m "chore: Ralph evolution update [skip ci]" || echo "No changes"
    git push origin main

availableSecrets:
  secretManager:
  - versionName: projects/bilkobibitkov/secrets/GITHUB_PAT/versions/latest
    env: 'GH_TOKEN'
  - versionName: projects/bilkobibitkov/secrets/GEMINI_API_KEY/versions/latest
    env: 'GEMINI_API_KEY'

options:
  logging: CLOUD_LOGGING_ONLY