steps:
# Step 1: Configure Git & Secret Access
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git config --global user.email "ralph-agent@bilkobibitkov.com"
    git config --global user.name "Ralph Agent"
    git remote set-url origin https://$$GH_TOKEN@github.com/BilkoBibitkov/bilko-bridge.git
    # Force the local branch name to 'main'
    git checkout -B main

# Step 2: Prepare Environment & Run Ralph
- name: 'python:3.11'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Install the missing brain library
    pip install google-genai
    
    # Run Ralph
    chmod +x ralph.sh
    ./ralph.sh 5

# Step 3: Push changes back to GitHub
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git add .
    git commit -m "chore: Ralph evolution update [skip ci]" || echo "No changes"
    # Push explicitly to main
    git push origin main

availableSecrets:
  secretManager:
  - versionName: projects/bilkobibitkov/secrets/GITHUB_PAT/versions/latest
    env: 'GH_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
