steps:
  # --- Step 0: Git Prep ---
  - name: 'gcr.io/cloud-builders/git'
    id: 'Git Configuration'
    secretEnv: ['GH_TOKEN']
    script: |
      #!/usr/bin/env bash
      git config --global --add safe.directory /workspace
      git config --global user.email "ralph@bilkobibitkov.com"
      git config --global user.name "Ralph (AI Architect)"
      git remote set-url origin https://$GH_TOKEN@github.com/BilkoBibitkov/bilko-bridge.git
      git checkout -B main

  # --- Step 1: Model Selection ---
  - name: 'gcr.io/bilkobibitkov/ralph-brain:latest'
    id: 'Probing Models'
    secretEnv: ['GOOGLE_API_KEY']
    script: |
      #!/usr/bin/env bash
      python bridge.py --probe || echo "Warning: Primary model capacity low."

  # --- Step 2: The Sovereign Brain (Ralph) ---
  - name: 'gcr.io/bilkobibitkov/ralph-brain:latest'
    id: 'Ralph Evolution'
    secretEnv: [
      'GOOGLE_API_KEY', 
      'FIREBASE_API_KEY', 
      'FIREBASE_PROJECT_ID', 
      'FIREBASE_AUTH_DOMAIN', 
      'FIREBASE_ADMIN_KEY',
      'AMP_API_KEY',
      'RALPH_SERVICE_KEY'
    ]
    script: |
      #!/usr/bin/env bash
      set -e
      # Standard Firebase Client Env
      export NEXT_PUBLIC_FIREBASE_API_KEY=$FIREBASE_API_KEY
      export NEXT_PUBLIC_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
      export NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
      
      # New Sovereign Power Injections
      export AMP_API_KEY=$AMP_API_KEY
      echo "$FIREBASE_ADMIN_KEY" > service-account.json
      echo "$RALPH_SERVICE_KEY" > ralph-key.json
      
      chmod +x ralph.sh
      ./ralph.sh 5

  # --- Step 3: Build & Deploy ---
  - name: 'node:20'
    id: 'App Build'
    script: |
      #!/usr/bin/env bash
      npm install
      npm run build
  - name: 'gcr.io/bilkobibitkov/firebase'
    id: 'Firebase Deploy'
    args: ['deploy', '--only', 'hosting', '--project', 'bilkobibitkov']

  # --- Step 4: Sync ---
  - name: 'gcr.io/cloud-builders/git'
    id: 'Push Evolution'
    secretEnv: ['GH_TOKEN']
    script: |
      #!/usr/bin/env bash
      git add .
      git commit -m "chore: Sovereign Ralph update [skip ci]" || echo "No changes"
      git push origin main

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/GITHUB_PAT/versions/latest
    env: 'GH_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
    env: 'GOOGLE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_API_KEY/versions/latest
    env: 'FIREBASE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PROJECT_ID/versions/latest
    env: 'FIREBASE_PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_AUTH_DOMAIN/versions/latest
    env: 'FIREBASE_AUTH_DOMAIN'
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_ADMIN_KEY/versions/latest
    env: 'FIREBASE_ADMIN_KEY'
  - versionName: projects/$PROJECT_ID/secrets/AMP_API_KEY/versions/latest
    env: 'AMP_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/ralph-key/versions/latest
    env: 'RALPH_SERVICE_KEY'

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
timeout: '1500s'