steps:
# Step 1: Git Configuration & Case-Sensitivity Fix
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git config --global user.email "ralph-agent@bilkobibitkov.com"
    git config --global user.name "Ralph Agent"
    git remote set-url origin https://$$GH_TOKEN@github.com/BilkoBibitkov/bilko-bridge.git
    git checkout -B main
    # Ensure Ralph sees 'prd.json'
    if [ -f "PRD.json" ]; then cp PRD.json prd.json; fi

# Step 2: Evolution (Ralph)
- name: 'python:3.11'
  secretEnv: ['GEMINI_API_KEY']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pip install google-genai
    # Inject the key directly into the environment
    export GEMINI_API_KEY=$$GEMINI_API_KEY
    chmod +x ralph.sh
    ./ralph.sh 5

# Step 3: Build Site
- name: 'node:20'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm install
    npm run build

# Step 4: Deploy to Firebase
- name: 'gcr.io/cloud-builders/firebase'
  args: ['deploy', '--only', 'hosting', '--project', 'bilkobibitkov']

# Step 5: Push Evolution back to GitHub
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git add .
    git commit -m "chore: Ralph evolution update [skip ci]" || echo "No changes"
    git push origin main

availableSecrets:
  secretManager:
  - versionName: projects/bilkobibitkov/secrets/GITHUB_PAT/versions/latest
    env: 'GH_TOKEN'
  - versionName: projects/bilkobibitkov/secrets/GEMINI_API_KEY/versions/latest
    env: 'GEMINI_API_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
