steps:
  # --- Step 0: Git Prep & Auth ---
  - name: 'gcr.io/cloud-builders/git'
    id: 'Git Configuration'
    secretEnv: ['GH_TOKEN']
    script: |
      #!/usr/bin/env bash
      git config --global --add safe.directory /workspace
      git config --global user.email "ralph@bilkobibitkov.com"
      git config --global user.name "Ralph (AI Architect)"
      git remote set-url origin https://$GH_TOKEN@github.com/BilkoBibitkov/bilko-bridge.git
      git checkout -B main

  # --- Step 1: The Radar (Probe) ---
  - name: 'gcr.io/bilkobibitkov/ralph-brain:latest'
    id: 'Probing Models'
    secretEnv: ['GOOGLE_API_KEY']
    script: |
      #!/usr/bin/env bash
      chmod +x probe.sh
      ./probe.sh

  # --- Step 2: The Sovereign Brain (Ralph) ---
  - name: 'gcr.io/bilkobibitkov/ralph-brain:latest'
    id: 'Ralph Evolution'
    secretEnv: ['GOOGLE_API_KEY', 'FIREBASE_API_KEY', 'FIREBASE_PROJECT_ID', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_ADMIN_KEY']
    script: |
      #!/usr/bin/env bash
      # 1. Export standard secrets for backward compatibility
      export NEXT_PUBLIC_FIREBASE_API_KEY=$FIREBASE_API_KEY
      export NEXT_PUBLIC_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
      export NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
      
      # 2. Inject the Sovereign Admin Key for Admin SDK tasks
      echo "$FIREBASE_ADMIN_KEY" > service-account.json
      
      # 3. Launch evolution
      chmod +x ralph.sh
      ./ralph.sh 5

  # --- Step 3: Application Build (Node) ---
  - name: 'node:20'
    id: 'App Build'
    script: |
      #!/usr/bin/env bash
      npm install
      npm run build

  # --- Step 4: Firebase Deployment ---
  - name: 'gcr.io/bilkobibitkov/firebase'
    id: 'Firebase Deploy'
    args: ['deploy', '--only', 'hosting', '--project', 'bilkobibitkov']

  # --- Step 5: State Synchronization ---
  - name: 'gcr.io/cloud-builders/git'
    id: 'Push Evolution'
    secretEnv: ['GH_TOKEN']
    script: |
      #!/usr/bin/env bash
      git add .
      git commit -m "chore: Ralph evolution update [skip ci]" || echo "No changes to sync"
      git push origin main

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/GITHUB_PAT/versions/latest
    env: 'GH_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
    env: 'GOOGLE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_API_KEY/versions/latest
    env: 'FIREBASE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PROJECT_ID/versions/latest
    env: 'FIREBASE_PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_AUTH_DOMAIN/versions/latest
    env: 'FIREBASE_AUTH_DOMAIN'
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_ADMIN_KEY/versions/latest
    env: 'FIREBASE_ADMIN_KEY'

timeout: '1200s'