options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1: Git Prep (Explicitly rooted in /workspace)
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  dir: '/workspace'
  script: |
    #!/usr/bin/env bash
    git config --global user.email "ralph-agent@bilkobibitkov.com"
    git config --global user.name "Ralph Agent"
    git remote set-url origin https://$$GH_TOKEN@github.com/BilkoBibitkov/bilko-bridge.git
    git checkout -B main
    if [ -f "PRD.json" ]; then cp PRD.json prd.json; fi

# Step 2: The Radar (Probe for Models)
- name: 'gcr.io/bilkobibitkov/ralph-brain:latest'
  secretEnv: ['GOOGLE_API_KEY']
  dir: '/workspace'
  script: |
    #!/usr/bin/env bash
    chmod +x probe.sh
    ./probe.sh

# Step 3: The Brain (Run Ralph)
- name: 'gcr.io/bilkobibitkov/ralph-brain:latest'
  secretEnv: ['GOOGLE_API_KEY']
  dir: '/workspace'
  script: |
    #!/usr/bin/env bash
    chmod +x ralph.sh
    ./ralph.