steps:
# Step 1: Git Prep
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  dir: '/workspace'
  script: |
    #!/usr/bin/env bash
    git config --global user.email "ralph-agent@bilkobibitkov.com"
    git config --global user.name "Ralph Agent"
    git remote set-url origin https://$$GH_TOKEN@github.com/BilkoBibitkov/bilko-bridge.git
    git checkout -B main
    if [ -f "PRD.json" ]; then cp PRD.json prd.json; fi

# Step 2: The Radar (Probe)
- name: 'gcr.io/bilkobibitkov/ralph-brain:latest'
  secretEnv: ['GOOGLE_API_KEY']
  dir: '/workspace'
  script: |
    #!/usr/bin/env bash
    chmod +x probe.sh
    ./probe.sh

# Step 3: The Brain (Ralph)
- name: 'gcr.io/bilkobibitkov/ralph-brain:latest'
  secretEnv: ['GOOGLE_API_KEY']
  dir: '/workspace'
  script: |
    #!/usr/bin/env bash
    chmod +x ralph.sh
    ./ralph.sh 5

# Step 4: Next.js Build
- name: 'node:20'
  dir: '/workspace'
  script: |
    #!/usr/bin/env bash
    npm install
    npm run build

# Step 5: Firebase Deploy
- name: 'gcr.io/bilkobibitkov/firebase'
  dir: '/workspace'
  args: ['deploy', '--only', 'hosting', '--project', 'bilkobibitkov']

# Step 6: Sync
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['GH_TOKEN']
  dir: '/workspace'
  script: |
    #!/usr/bin/env bash
    git add .
    git commit -m "chore: Ralph evolution update [skip ci]" || echo "No changes"
    git push origin main

options:
  substitution_option: ALLOW_LOOSE

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/GITHUB_PAT/versions/latest
    env: 'GH_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
    env: 'GOOGLE_API_KEY'